# Generated by Django 4.0.2 on 2022-04-30 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_name_en_category_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='categories.category'),
        ),
    ]
