# Generated by Django 4.0.2 on 2022-04-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='about_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='adult_price_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='adult_price_ru',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='children_price_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='children_price_ru',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price_en',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price_ru',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='partner_price_en',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='partner_price_ru',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_ru',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
